version: 0.2

phases:
  build:
    commands:
      - chmod +x mvnw
      - ./mvnw -DskipTests package
      - mkdir -p eb_bundle
      - cp Procfile eb_bundle/Procfile
      - cp target/*.jar eb_bundle/application.jar

artifacts:
  base-directory: eb_bundle
  files:
    - Procfile
    - application.jar
